# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
# development:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   database: d98b97i64le7q7
#   username: khhylpiqxxlkaq
#   password: 0ryeSyA6EuohN4j7CrojML9Ccw
#   host: ec2-54-225-102-116.compute-1.amazonaws.com
#   port: 5432

development:
  adapter: postgresql
  encoding: unicode
  database: djtweet_development
  pool: 5
  username: dibyo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: djtweet_test
  pool: 5
  username: dibyo
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: djtweet_production
  pool: 5
  username: bgapi
  password:
